-- Q7
SELECT CARTON_ID, LEN*WIDTH*HEIGHT 'CARTON_VOL' FROM CARTON WHERE LEN*WIDTH*HEIGHT > 
(SELECT SUM(LEN*WIDTH*HEIGHT*PRODUCT_QUANTITY) FROM ORDER_ITEMS OT JOIN PRODUCT P ON P.PRODUCT_ID = OT.PRODUCT_ID 
WHERE ORDER_ID=10006) order by  LEN*WIDTH*HEIGHT limit 1;
-- Q8
SELECT C.CUSTOMER_ID,CONCAT(C.CUSTOMER_FNAME , ' ' , C.CUSTOMER_LNAME) 'Customer_FullName', X.ORDER_ID,X.SUM 'PRODUCT_QUANTITY' FROM
(SELECT  OH.ORDER_ID,SUM(PRODUCT_QUANTITY) 'SUM' FROM ONLINE_CUSTOMER OC JOIN ORDER_HEADER OH 
ON OH.CUSTOMER_ID = OC.CUSTOMER_ID
JOIN ORDER_ITEMS OT ON OT.ORDER_ID = OH.ORDER_ID 
where PAYMENT_MODE IN ('Net Banking','Credit Card') AND ORDER_STATUS = 'Shipped'
group by OH.ORDER_ID having SUM(PRODUCT_QUANTITY) > 10) X JOIN ORDER_HEADER OH ON OH.ORDER_ID = X.ORDER_ID 
JOIN ONLINE_CUSTOMER C ON C.CUSTOMER_ID=OH.CUSTOMER_ID


show databases;
use hr;
show tables;

select *from employees;
select *from ipldb.auction_2021;

-- Question 9
SELECT  DISTINCT OH.ORDER_ID,OC.CUSTOMER_ID, CONCAT(CUSTOMER_FNAME,' ',CUSTOMER_LNAME) 'Customer Full Name',
SUM(OT.PRODUCT_QUANTITY) 'Total Quantity'
 FROM ONLINE_CUSTOMER OC JOIN ORDER_HEADER OH 
ON OH.CUSTOMER_ID = OC.CUSTOMER_ID
JOIN ORDER_ITEMS OT ON OT.ORDER_ID = OH.ORDER_ID 
where OH.ORDER_ID > 10030 AND ORDER_STATUS = 'Shipped' AND CUSTOMER_FNAME LIKE 'A%'
GROUP BY ORDER_ID

-- Question 10
SELECT PC.PRODUCT_CLASS_DESC,SUM(ITS.PRODUCT_QUANTITY) 'Total Quantity',(PRODUCT_QUANTITY*PRODUCT_PRICE)'Total Value' FROM
(SELECT  X.PRODUCT_CLASS_CODE FROM 
(select  P.PRODUCT_CLASS_CODE, SUM(ITM.PRODUCT_QUANTITY) 'SUM'
FROM ONLINE_CUSTOMER OC JOIN ORDER_HEADER OH ON OH.CUSTOMER_ID = OC.CUSTOMER_ID 
JOIN ADDRESS A ON A.ADDRESS_ID = OC.ADDRESS_ID AND OH.ORDER_STATUS = 'Shipped'
join order_items itm on itm.ORDER_ID = OH.ORDER_ID 
JOIN PRODUCT P ON P.PRODUCT_ID = itm.PRODUCT_ID 
join PRODUCT_CLASS C ON C.PRODUCT_CLASS_CODE = P.PRODUCT_CLASS_CODE
WHERE A.COUNTRY NOT IN ('USA','India') 
GROUP BY C.PRODUCT_CLASS_CODE) X order by X.SUM DESC LIMIT 1) Y JOIN 
PRODUCT P ON P.PRODUCT_CLASS_CODE =Y.PRODUCT_CLASS_CODE
JOIN ORDER_ITEMS ITS ON ITS.PRODUCT_ID = P.PRODUCT_ID
JOIN PRODUCT_CLASS PC ON PC.PRODUCT_CLASS_CODE= P.PRODUCT_CLASS_CODE
